- GitForWindowsHelper/check-runs.js
- GitForWindowsHelper/slash-commands.js
The neat trick of the `build-and-deploy` workflow is that it "mirrors" a check-run into the target repository.
But that check-run is currently only mirrored once the workflow runs and executes the respective step, which necessarily takes a few seconds because the workflow first has to check out the code to run the deployment.
Let's let the GitHub App already add the check-run, in `queued` state, to provide a more immediate visual feedback to the `/deploy` command.
> /deploy: immediately queue check-run

- test-pr-comment-delivery.js
The GitHub app has been [transferred to the git-for-windows organization]( https://github.com/git-for-windows/gfw-helper-github-app/issues/11#issuecomment-1351362989), which changed the URL for the settings. Change the comments mentioning the old URL to the new URL.
There is one remaining mention of the old URL in README.md, but that mention is in the historical context of how the app was created, so keeping the old URL is appropriate
> update settings URL

- GitForWindowsHelper/component-updates.js
- GitForWindowsHelper/slash-commands.js
Our component monitoring can aggregate multiple issues into one if it would open multiple issues for the same component at the same time.  We need to treat these issues different from other issues, because their title doesn't contain version information.
This fixes #11
> Support aggregated issues

- GitForWindowsHelper/component-updates.js
- GitForWindowsHelper/slash-commands.js
[I noticed this morning](https://github.com/git-for-windows/MSYS2-packages/pull/70#issuecomment-1357489945) that `git-sdk-32` unexpectedly failed to update MinTTY to v3.6.3, and figured out that it was simply an oversight on my part in forgetting to implement the `/deploy` side of MSYS packages' builds, and therefore only the x86_64 package was built (and that one quite by happy mistake).
This PR introduces support for `/deploy`ing MSYS packages (the `git-for-windows-automation` workflow was [already prepared for it in advance](https://github.com/git-for-windows/git-for-windows-automation/commit/349e4e17451b3a8be428e8f81a62f57db7620efa).
> Deploy i686 MSYS packages too, not only x86_64 ones

- GitForWindowsHelper/check-runs.js
- GitForWindowsHelper/slash-commands.js
GitHubs check runs provide a neat little "view more details" link (see for example https://github.com/git-for-windows/build-extra/pull/451/checks?check_run_id=10110786774) That should allow users to view the status of the check run (beyond running/queued/success/failure). For our check runs it currently just links to https://github.com/git-for-windows/gfw-helper-github-app, but we can populate the URL to link to the actual workflow run we're waiting for.
> /deploy: populate Details URL

- .eslintrc.json
- GitForWindowsHelper/azure-pipelines.js
- GitForWindowsHelper/check-runs.js
- GitForWindowsHelper/get-collaborator-permissions.js
- GitForWindowsHelper/github-api-request-as-app.js
- GitForWindowsHelper/https-request.js
- GitForWindowsHelper/index.js
- GitForWindowsHelper/self-hosted-arm64-runners.js
- GitForWindowsHelper/slash-commands.js
- GitForWindowsHelper/trigger-workflow-dispatch.js
With these changes (that require https://github.com/git-for-windows/git-for-windows-automation/pull/11 to be merged first), we will have automation in place where starting a workflow job in `git-for-windows/git-for-windows-automation` that requires an ARM64 runner will automatically spin up the required runner and delete the VM after use.
NOTE: This is not yet fully tested, I basically only verified that [an unauthorized build can be successfully canceled](https://github.com/git-for-windows/git-for-windows-automation/pull/13) (I patched the code locally to pretend that I am not authorized). I plan on fully testing this later, using [the `mingw-w64-clang-aarch64-xpdf` build](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3881130673) to trigger said workflow job, …
> Automatically spin up/tear down self-hosted ARM64 runners

- GitForWindowsHelper/component-updates.js
- GitForWindowsHelper/slash-commands.js
Let's also build the `clang-aarch64` packages, since we can.
> /deploy: also trigger clang-aarch64 builds when appropriate

- GitForWindowsHelper/component-updates.js
- test-open-pr.js
- test-pr-comment-delivery.js
Seems that even [if OpenSSL re-announced their version with dots in the version string](https://github.com/git-for-windows/git/issues/4277#issuecomment-1422243185) that we mishandled version strings with multiple underscores.
Let's fix that.
> /open pr: handle multiple underscores in the reported version

- GitForWindowsHelper/component-updates.js
- GitForWindowsHelper/slash-commands.js
- test-guess-relnote.js
When issuing an `/add release note` without any further information, we try to auto-generate a sensible message from the context.
While looking into adding a release note for Bash in https://github.com/git-for-windows/git/issues/4164, I realized that that logic is pretty much failing completely for that package.
Here is my attempt to fix that.
> Improve the logic to guess release notes in `/add release note`

- .vscode/launch.json
- GitForWindowsHelper/cascading-runs.js
- GitForWindowsHelper/check-runs.js
- GitForWindowsHelper/index.js
- GitForWindowsHelper/issues.js
- GitForWindowsHelper/slash-commands.js
- __tests__/index.test.js
This is the companion to https://github.com/git-for-windows/git-for-windows-automation/pull/38 that concludes Git for Windows' release process' journey off of Azure Pipelines.
With this PR, the `/git-artifacts` command triggers a `tag-git` workflow run, upon whose mirrored Check Run's conclusion the `git-artifacts` runs are triggered. And the `/release` picks up those runs and triggers the `release-git` workflow run.
I intend to verify the correctness of this PR (and to fix whatever is necessary) with `-rc2` which is [supposed to be released today](https://tinyurl.com/gitcal).
> Switch `/git-artifacts` and `/release` to trigger GitHub workflows instead

- .vscode/launch.json
- GitForWindowsHelper/slash-commands.js
- __tests__/index.test.js
From here on out, we will build `msys2-runtime-3.3` only for i686, and `msys2-runtime` only for x86_64. This is a necessary prerequisite for upgrading `msys2-runtime` to the current version, v3.4.6, because that simply does not support i686 anymore (and to accommodate for that, we move `git-sdk-32` to using `msys2-runtime-3.3` instead of `msys2-runtime`).
> Prepare for the architecture split between MSYS2 runtime 3.3.* vs 3.4.*

- GitForWindowsHelper/component-updates.js
- __tests__/component-updates.test.js
The `/open pr` automation failed in https://github.com/git-for-windows/git/issues/4439, not only because the `curl.haxx.se/download` links no longer work, and not only because `.tar.bz2` files are at https://github.com/curl/curl/releases now instead of `.tar.xz` files, but also because the RSS feed item format changed.
Let's fix that, and while at it, reinstate the better links to cURL's release notes that we used to provide in the good old `please.sh upgrade curl` times.
> Guess better cURL release notes

- GitForWindowsHelper/component-updates.js
- __tests__/component-updates.test.js
We would like to show useful links in the release notes for new OpenSSL versions, just like [we did before we switched from using `please.sh upgrade openssl` to branch deployments](https://github.com/git-for-windows/build-extra/blob/d488d45e052b/please.sh#L1930-L1932).
This is a sibling to #34.
> guess release notes: special-case OpenSSL

- GitForWindowsHelper/slash-commands.js
- __tests__/index.test.js
we're not using clang to build for other architectures, so we don't need to build it for other architectures
This is a companion PR to https://github.com/git-for-windows/MINGW-packages/pull/75
> /deploy: only build mingw-w64-clang for ARM64

- .github/workflows/pr.yml
As per https://github.com/nodejs/release#release-schedule node.js 16.x is only in maintenance mode. Prior to switching over this here GitHub App from node.js 16.x to 18.x, make sure that it actually works with that node.js version.
> PR: test with node.js 18.x

- GitForWindowsHelper/azure-pipelines.js
- GitForWindowsHelper/component-updates.js
- GitForWindowsHelper/github-api-request-as-app.js
- GitForWindowsHelper/github-api-request.js
- GitForWindowsHelper/https-request.js
- GitForWindowsHelper/search.js
- GitForWindowsHelper/slash-commands.js
- __tests__/component-updates.test.js
- __tests__/index.test.js
It is all too easy to run `/add release note` in a `component-update` ticket, and easy to miss that the package files have not been deployed (or that a deployment failed). This happened e.g. [here](https://github.com/git-for-windows/git/issues/4523).
This PR adds automation to help prevent such issues in the future, by verifying whether the corresponding package files have been deployed (and complaining loudly if any deployed files are missing).
> Make `/add relnote` safer to use

- GitForWindowsHelper/component-updates.js
- __tests__/component-updates.test.js
In the Pacman universe, there is the concept of an "epoch", which is part of the versioning scheme and which has more weight than the `pkgver` value.
This concept allows following projects which "re-set" their version, for example (e.g. switching from a date-based "version" to an actual version that would naturally sort way below the previous date-based one).
In the Git for Windows project, we incremented the epoch of the `mintty` package, originally simply to override MSYS2's `mintty`, even if that was technically not even necessary.
Yet it is part of Git for Windows' legacy that the `/add release note` command needs to keep in mind when trying to verify that the `mintty` packages have been deployed properly.
Thankfully, `mintty` is the only package built by Git for Windows that has an …
> /add relnote: respect MinTTY's "epoch"

- GitForWindowsHelper/component-updates.js
- __tests__/component-updates.test.js
Over in https://github.com/git-for-windows/git/issues/4593#issuecomment-1710125267, I tried to add a release note, which got refused because the i686 variant of the MSYS2 runtime was not deployed. This is actually correct, but GitForWindowsHelper's expectations about that are incorrect, so let's adjust the latter.
> Adjust `msys2-runtime` deployment expectations

- GitForWindowsHelper/component-updates.js
- __tests__/component-updates.test.js
OpenSSH likes to use a very funny version number format on their website, a format that we cannot use in Pacman packages, and therefore it needs to be transmogrified just like we did in
https://github.com/git-for-windows/git-for-windows-automation/pull/27 when checking for missing deployments.
> missing-deployments: learn to handle OpenSSH's version number

- GitForWindowsHelper/cascading-runs.js
- GitForWindowsHelper/github-api-request.js
- GitForWindowsHelper/issues.js
- __tests__/index.test.js
When a `/git-artifacts` is issued with an existing corresponding `tag-git` run, the respective comment is updated immediately with links to the `git-artifacts-*` runs.
However, when that `tag-git` run does not exist, the comment is updated with a link to the newly-triggered `tag-git` run, and when that run's completion triggers the "cascading" `git-artifacts-*` runs, the PR comment is no longer updated.
This is unfortunate because that information is rather valuable and saves time e.g. when trying to manually validate the generated installer.
So let's try a little harder to find that comment, and update it.
This fixes https://github.com/git-for-windows/gfw-helper-github-app/issues/38.
> Update the `/git-artifacts` PR comment even in cascading runs

- GitForWindowsHelper/component-updates.js
- __tests__/component-updates.test.js
[This](https://github.com/git-for-windows/MSYS2-packages/pull/132#issuecomment-1806927187) just happened:
> /add relnote
>
> The following deployment(s) are missing:
>
> https://wingit.blob.core.windows.net/i686/bash-5.2.21-1-i686.pkg.tar.xz
> https://wingit.blob.core.windows.net/x86-64/bash-5.2.21-1-x86_64.pkg.tar.xz
> 😦 
The reason is that the patch-level of the Bash package [is 0-padded to 3 digits](https://github.com/git-for-windows/MSYS2-packages/blob/8612db42be8ed99301f867991daa093f37f121ba/bash/PKGBUILD#L7) (see also [here](https://github.com/git-for-windows/git-for-windows-automation/blob/10edc10b4cffc77ab7ada4c0466de6224debc2dc/update-scripts/version/bash#L21)).
Let's fix this in the GitForWindowsHelper, too.
> missing-deployments: learn about the Bash package's version scheme

- GitForWindowsHelper/github-api-request-as-app.js
- GitForWindowsHelper/issues.js
In #47 I tried to teach GitForWindowsHelper to find the PR comment containing `/git-artifacts` when the `tag-git` check run finished that was triggered by that slash command. However, it did not work, despite the webhook being delivered with status 200 and the response body being:
> The `git-artifacts-x86_64` workflow run [was started](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/6869163398).
> The `git-artifacts-i686` workflow run [was started](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/6869164014).
I do not really know why it failed, but when I tried to run the code locally (commenting out the part that would have triggered another pair of `git-artifacts` runs), it didn't work for me either, due to expire time issues ("too …
> Update `tag-git` comment in cascading runs; Follow up

- GitForWindowsHelper/component-updates.js
I already added special-casing for GNU TLS in 2085119 (guess release notes: support GNU TLS tickets better, 2023-02-15), but I forgot that it's also possible to call `/add relnote` from the `mingw-w64-gnutls` Pull Request... Let's remedy that.
This fixes https://github.com/git-for-windows/gfw-helper-github-app/issues/51
> /add relnote: extend `gnutls` special-casing to the MINGW variant

- GitForWindowsHelper/component-updates.js
- __tests__/component-updates.test.js
https://github.com/git-for-windows/git/issues/4712 has shown us that our current handling of GPG updates is still a little bumpy.
> Handle GPG updates better

- delete-bogus-installations.js
- get-webhook-event-payload.js
These scripts are meant for local use, i.e they are not intended to be run on the server side.
> Add two convenience scripts

- GitForWindowsHelper/slash-commands.js
- README.md
- __tests__/index.test.js
Marked as draft because it needs https://github.com/git-for-windows/git-for-windows-automation/pull/62 to be merged first.
As with most of the other slash commands, this triggers a GitHub workflow run in `git-for-windows-automation`, in this instance, unsurprisingly the `upkpkgsums.yml` one.
The idea is to help contributors with their Pull Requests that fail CI builds solely due to mismatched checksums after modifying, adding or removing files from a package.
This fixes #28.
> Add the `/updpkgsums` slash command

- get-webhook-event-payload.js
Previously, I only showed the request. But that's not all of the good information that we can have: Most notably, we can also show the response, which is particularly interesting in case things go wrong.
> get-webhook-event-payload: show the entire event

- GitForWindowsHelper/slash-commands.js
- __tests__/index.test.js
It will become increasingly more normal for Git for Windows to be forced to build packages for i686 just because they are dependencies of packages we _want_ to build but a newer dependency version is required (and the MSYS2 project no longer blesses us with i686 variants of MSYS packages).
So let's establish this pattern: If the PR title starts with `i686:`, it is meant only to build and deploy an i686 package, does not require any release notes, and certainly no x86_64 build.
I will use this to deploy the i686 variant of `libkbsa` (which is needed because the newest `gnupg` is no longer happy with version 1.6.0 of that library) in https://github.com/git-for-windows/MSYS2-packages/pull/153.
> Prepare `/deploy` for i686-only Pull Requests

- .github/dependabot.yml
See https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#enabling-dependabot-version-updates-for-actions for details.
> dependabot: help keeping npm packages & GitHub Actions versions up to date

- GitForWindowsHelper/finalize-g4w-release.js
- GitForWindowsHelper/index.js
- __tests__/index.test.js
- get-webhook-event-payload.js
- test-pr-comment-delivery.js
I outlined the idea [here](https://github.com/git-for-windows/git-for-windows-automation/pull/73#issuecomment-1959096816). The gist is:
Let's listen for completed `release-git` workflow runs in the `git-for-windows-automation` repository. The trick is to get from that workflow run to the corresponding `git-for-windows/git` PR because there is no information in the Get a Check Run response to get back to the `git-for-windows/git` PR or tag or commit (example: https://api.github.com/repos/git-for-windows/git-for-windows-automation/actions/runs/7978659901).
Sadly, searching for a PR comment containing the workflow run ID won't work because the REST API search endpoint searches the rendered text, not the Markdown. But we can [search for an open PR with the …
> After a Git for Windows version has been released, automatically close the corresponding PR

- GitForWindowsHelper/cascading-runs.js
- GitForWindowsHelper/issues.js
- __tests__/index.test.js
Over in https://github.com/git-for-windows/git/pull/4918, _something_ in the range-diff was matched _somehow_ by that search string. The `text_matches` of the returned objects look like this:
```yaml
text_matches: [
{
object_url: "https://api.github.com/repositories/23216272/issues/comments/2067288321",
object_type: "IssueComment",
property: "body",
fragment: "/git-artifacts\n\nThe tag-git workflow run was started\n",
matches: [
{
text: "git",
indices: [
1,
4,
],
},
{
text: "artifacts",
indices: [
5,
14,
],
},
{
text: "git",
indices: [
24,
27,
],
},
],
},
{
object_url: "https://api.github.com/repositories/23216272/issues/4918",
object_type: "Issue",
property: "body",
fragment: " = 53: 33d9a68ea63 vcxproj: handle GUI programs, too\n\n  - 55: 417ce96c240 = 54: 4c3acea6c21 ci(vs-build) also …
```
> Find the `/git-artifacts` comment even more reliably

- GitForWindowsHelper/index.js
The `sync` job in said repo currently runs on x64 runners, which is problematic in case post-install scripts need to run.
Let's support ARM64 self-hosted runners on that repo too.
> self-hosted-arm64-runners: enable on git-sdk-arm64 repo too

- GitForWindowsHelper/self-hosted-arm64-runners.js
The create-azure-self-hosted-runners workflow has an input called `runner_repo` which can be used to specify the repository that the runner will be deployed to. It defaults to git-for-windows-automation, which is not the right one in all cases.
Let's set the `runner_repo` input to the repository that requested the runner.
Ref: https://github.com/git-for-windows/git-for-windows-automation/blob/main/.github/workflows/create-azure-self-hosted-runners.yml#L18C7-L18C18
> self-hosted-arm64-runners: specify target repo

- GitForWindowsHelper/component-updates.js
- GitForWindowsHelper/slash-commands.js
- __tests__/index.test.js
MSYS2 [renamed the mingw-w64-clang folder to mingw-w64-llvm](https://github.com/msys2/MINGW-packages/commit/2ad570ca96fbb35cc408763f1a4d421801466fb8), adjust the `/deploy command to handle this change gracefully.
> /deploy: adjust for new mingw-w64-clang name

- GitForWindowsHelper/slash-commands.js
- __tests__/index.test.js
- get-webhook-event-payload.js
Even after https://github.com/git-for-windows/git-for-windows-automation/pull/82, [the `/updpkgsums` call](https://github.com/git-for-windows/build-extra/pull/558#issuecomment-2154366214) over in https://github.com/git-for-windows/build-extra/pull/558 failed.
While this PR won't fix it completely, it fixes the GitForWindowsHelper GitHub App side of it.
> Fix `/updpkgsums`

- .vscode/launch.json
- GitForWindowsHelper/component-updates.js
- GitForWindowsHelper/slash-commands.js
- __tests__/index.test.js
This is the logical companion to https://github.com/git-for-windows/git-for-windows-automation/pull/87.
The idea is that PRs like https://github.com/git-for-windows/msys2-runtime/pull/69 can be integrated easily via running `/open pr` and then, in the newly-created PR, running `/deploy`.
> `/open pr`: support running in git-for-windows/msys2-runtime PRs

- GitForWindowsHelper/component-updates.js
- __tests__/component-updates.test.js
Git for Windows now also receives new tickets whenever a new InnoSetup version has been tagged. Therefore it makes sense to teach the `/open pr` machinery about this component, too.
Note that the `open-pr` GitHub workflow also needs to be adjusted slightly, I have patches in hand but could not validate them yet because [the new InnoSetup installer is not yet available for download](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/9907166552/job/27370261636#step:9:44).
EDIT: The `open-pr` GitHub workflow is updated [here](https://github.com/git-for-windows/git-for-windows-automation/pull/88).
> Teach the app about InnoSetup

- GitForWindowsHelper/component-updates.js
- __tests__/component-updates.test.js
In https://github.com/git-for-windows/gfw-helper-github-app/pull/34, I taught the GitForWindowsHelper GitHub App to generate better release notes for cURL.
However, I failed to notice that the code changes would work only for the `component-updates` issues as well as for the MSYS2-packages PRs, but not for the MINGW-packages PRs because the package name that is derived from the latter PRs has the `mingw-w64-` prefix (and must have it, for the "is this already deployed?" check).
Let's make sure that that special-casing (as well for cURL as well as for OpenSSL) work even in MINGW-packages PRs.
> guess release notes: special-case cURL (even in MINGW-packages)

- GitForWindowsHelper/cascading-runs.js
- __tests__/index.test.js
This implements the change mentioned in https://github.com/git-for-windows/git/issues/3107#issuecomment-2470306746.
The `git-artifacts` pipeline supports ARM64 (aarch64) since a couple months. We've been triggering the pipeline manually until now, with good results, so let's start triggering it automatically moving forward.
> cascading-runs: also build ARM64 artifacts

- GitForWindowsHelper/slash-commands.js
- __tests__/index.test.js
We're already building arm64 artifacts, so let's add support for arm64 to the release pipeline as well. Note: this needs the workflow to support the `git_artifacts_aarch64_workflow_run_id` input as well.
> slash-commands: support arm64 in release command

- .vscode/settings.json
- GitForWindowsHelper/slash-commands.js
- README.md
Every once in a while I need to ensure that the packages that were just deployed via a `/deploy` command are integrated into the respective `git-sdk-*` repositories so that a subsequent `/git-artifacts` run will pick up the just-deployed package versions.
This PR adds the convenient `/sync` command for that, which [I just used successfully](https://github.com/git-for-windows/MSYS2-packages/pull/211#issuecomment-2624294399) (running this PR's code locally because it is obviously not yet deployed to the Azure Function).
> Add a slash command to synchronize Git for Windows' SDK repositories

- get-webhook-event-payload.js
When we run out of payloads to iterate on, we may well operate on `null` objects when trying to access the `epoch` attribute.
Let's be more careful about that.
> get-webhook-event-payload: be more careful about missing `epoch`s

- GitForWindowsHelper/cascading-runs.js
- GitForWindowsHelper/finalize-g4w-release.js
- __tests__/index.test.js
When publishing Git for Windows v2.48.1, two bugs became obvious:
- Directly after `/git-artifacts` finished, the `upload-snapshot` workflow was run, and [it failed](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/13307618060/job/37162142657#step:7:43) (because it was started before I could even validate the installers let alone release them, and therefore the corresponding commit was not yet reachable from `main`).
- When I finally was ready to `/release`, everything worked fine except that the `upload-snapshot` run was _not_ triggered (I had to manually trigger [a re-run](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/13307618060/job/37164420059) of the previously-canceled one to upload [the …
> Fix the snapshot uploading of official Git for Windows versions

- GitForWindowsHelper/component-updates.js
- __tests__/component-updates.test.js
- __tests__/index.test.js
I just tried running that slash command in https://github.com/git-for-windows/git/issues/5398 and it failed. Let's fix that.
While at it, I noticed that the ARM64 packages aren't checked, so let's fix that, too.
> Fix PCRE2 `/add release note`

- GitForWindowsHelper/cascading-runs.js
- GitForWindowsHelper/check-runs.js
- GitForWindowsHelper/finalize-g4w-release.js
- __tests__/index.test.js
There are two situations when [the `upload-snapshot` workflow](https://github.com/git-for-windows/git-for-windows-automation/actions/workflows/upload-snapshot.yml) needs to be triggered:
1. For regular updates of Git for Windows:
1. A regular `git-for-windows/git` PR is merged, which means that `main` is updated.
2. This triggers a [`tag-git` workflow](https://github.com/git-for-windows/git-for-windows-automation/actions/workflows/tag-git.yml) run with the `snapshot` flag set to `true`.
3. Once that `tag-git` run completes, GitForWindowsHelper triggers [`git-artifacts` workflow](https://github.com/git-for-windows/git-for-windows-automation/actions/workflows/git-artifacts.yml) runs for x86_64, aarch64 and i686 each.
4. Once the last of these three `git-artifacts` runs completes with …
> Fix `upload-snapshot` on `push`

- README.md
Git for Windows' wiki pages migrated to its home page as of https://github.com/git-for-windows/git-for-windows.github.io/pull/59; Let's adjust the one link in this here repository to point to that new location.
> Replace a superseded URL that pointed to Git for Windows' wiki
